### ISSUE TITLE
how to we build with costumize bootnodes and ENR for first time?

### ISSUE THREAD

**Issue by avenbreaks** [ephemery-testnet/ephemery-genesis#11]
how do i get & change bootnodes, enr for first time run ?

**Comment by pk910** [comment]
Heya @avenbreaks,
Sorry for the late response, I haven't really seen this issue earlier 😅

We're using a generic eth2 bootnode for the CL side. 
It is "generic", because it builds an ENR that is not bound to a specific network fork version. Quite optimal for testnets with a changing forkversion ;)
You can find that tool here:  https://github.com/protolambda/eth2-bootnode

On EL side, we're simply using a geth instance. The enode is printed on startup  and isn't bound to a chainid or so.
